services:
  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    env_file:
      - .env
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    # or unless-stopped?
    restart: always
  
  wordpress:
    depends_on:
      - mariadb
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    container_name: wordpress
    env_file: 
      - .env
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    restart: always

  nginx:
    depends_on:
      - wordpress
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "8000:80"
      - "443:443"
    volumes:
      - wordpress:/var/www/html
      - ./requirements/nginx/tools/ssl:/etc/nginx/ssl:ro
    networks:
      - inception
    restart: always

# named volumes that map back to a local directory
volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      device: $HOME/data/mariadb
      o: bind
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: $HOME/data/wordpress
      o: bind

networks:
  inception:
    driver: bridge
