services:
  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    #volumes:
    #networks

  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    #ports:
    #environment: use .env to populate environment variables
      #MYSQL_ROOT_PASSWORD: root
      #MYSQL_DATABASE: wordpress
      #MYSQL_USER: wordpress
      #MYSQL_PASSWORD: wordpress
    #volumes: specify volume --> how/where to create volume? in VM? script?
      
    #networks:

#networks:
