services:
  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    #necessary?
    ports:
      - "3306:3306"
    #necessary?
    env_file: .env
    environment:
      - WP_HOST=wordpress:9000
      - MYSQL_DB=$MYSQL_DATABASE
      - MYSQL_USER=$MYSQL_USERNAME
      - MYSQL_PASS=$MYSQL_PASSWORD
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    # or unless-stopped?
    restart: always
  
  wordpress:
    depends_on:
      - mariadb
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    container_name: wordpress
    env_file: .env
    environment:
      - DB_HOST=mariadb:3306
      - DB_NAME=$MYSQL_DATABASE
      - DB_USER=$MYSQL_USERNAME
      - DB_PASS=$MYSQL_PASSWORD
      - WP_URL=$HOST
      - WP_ADMIN_USER=$WORDPRESS_ADMIN_USER
      - WP_ADMIN_PASS=$WORDPRESS_ADMIN_PASS
      - WP_ADMIN_EMAIL=$WORDPRESS_ADMIN_EMAIL
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    restart: always

  nginx:
    depends_on:
      - wordpress
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "8000:80"
    #This will mount the WordPress application code to the /var/www/html directory, the directory set as the root in the Nginx server block
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    restart: always

volumes:
  mariadb:
  wordpress:

networks:
  inception:
    driver: bridge
