services:
  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    env_file:
      - .env
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    #healthcheck:
     # test: ["CMD-SHELL", "pg_isready"]
      #interval: 10s
      #timeout: 5s
      #retries: 5
    restart: always
  
  wordpress:
    depends_on:
      - mariadb
       #mariadb:
        #condition: service_healthy
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    container_name: wordpress
    env_file: 
      - .env
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    restart: always

  nginx:
    depends_on:
      - wordpress
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "8000:80" # may remove
      - "443:443"
    volumes:
      - wordpress:/var/www/html
      - ./requirements/nginx/tools/ssl:/etc/nginx/ssl:ro
    networks:
      - inception
    restart: always

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      device: $HOME/data/mariadb
      o: bind
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: $HOME/data/wordpress
      o: bind

networks:
  inception:
    driver: bridge
