services:
  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    ports:
      - "3306:3306"
    #necessary?
    env_file: .env
    #use .env to populate environment variables
    environment: 
      - MTSQL_DATABASE=wordpress
      #MYSQL_ROOT_PASSWORD: root
      #MYSQL_DATABASE: wordpress
      #MYSQL_USER: wordpress
      #MYSQL_PASSWORD: wordpress
    #specify volume --> how/where to create volume? in VM? script?
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    # or unless-stopped?
    restart: always
  
  wordpress:
    depends_on:
      - mariadb
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    container_name: wordpress
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=mariadb:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=wordpress
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    restart: always

  nginx:
    depends_on:
      - wordpress
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "8000:80"
    #This will mount the WordPress application code to the /var/www/html directory, the directory set as the root in the Nginx server block
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    restart: always

volumes:
  mariadb:
  wordpress:

networks:
  inception:
    driver: bridge
